name: app_lele
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  sqflite: ^2.4.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  motion_toast: ^2.11.0
  path: ^1.9.0
  cloud_firestore: ^5.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  awesome_notifications: ^0.10.0
  awesome_notifications_fcm: ^0.10.0
  fluttertoast: ^8.2.8
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
